title: Project CONCRETE
description: Developing new digital foundations
theme: just-the-docs

url: https://BigMassive.github.io/CONCRETE

permalink: pretty

defaults:
  - scope:
      path: "site_content" 
      type: "pages"
    values:
      layout: "default"

heading_anchors: true

callouts:
  note:
    title: Note
    color: blue
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  warning:
    title: Warning
    color: red
  quote:
    color: grey-lt

nav_enabled: true

favicon_ico: "/images/current/concrete_icon.ico"

mermaid:
  version: "11.6.0"

